edition = "2024"

unstable_features = true

combine_control_expr = false
blank_lines_upper_bound = 2
enum_discrim_align_threshold = 40
force_multiline_blocks = true
imports_layout = "HorizontalVertical"
max_width = 160
imports_granularity = "Module"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
where_single_line = true
use_small_heuristics = "Max"
single_line_if_else_max_width = 50
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = false
format_code_in_doc_comments = false
format_generated_files = false
